"""add phase 6 training schema

Revision ID: 0274cb5eb6c5
Revises: 9e6c00e1c16d
Create Date: 2026-09-13 17:10:45.294133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0274cb5eb6c5'
down_revision: Union[str, None] = '9e6c00e1c16d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clients',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('organization_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=True),
    sa.Column('partition_type', sa.String(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_client_id'), 'clients', ['client_id'], unique=True)
    op.create_table('experiments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('experiment_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('dataset_name', sa.String(), nullable=True),
    sa.Column('dataset_subset', sa.String(), nullable=True),
    sa.Column('model_type', sa.String(), nullable=False),
    sa.Column('strategy', sa.String(), nullable=False),
    sa.Column('partition_type', sa.String(), nullable=True),
    sa.Column('num_clients', sa.Integer(), nullable=False),
    sa.Column('num_rounds', sa.Integer(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiments_experiment_id'), 'experiments', ['experiment_id'], unique=True)
    op.create_table('training_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('experiment_id', sa.String(), nullable=True),
    sa.Column('model_type', sa.String(), nullable=False),
    sa.Column('strategy', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('num_clients', sa.Integer(), nullable=False),
    sa.Column('num_rounds', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('artifact_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.experiment_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_runs_run_id'), 'training_runs', ['run_id'], unique=True)
    op.create_table('global_metrics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('precision', sa.Float(), nullable=True),
    sa.Column('recall', sa.Float(), nullable=True),
    sa.Column('f1', sa.Float(), nullable=True),
    sa.Column('roc_auc', sa.Float(), nullable=True),
    sa.Column('pr_auc', sa.Float(), nullable=True),
    sa.Column('false_positive_rate', sa.Float(), nullable=True),
    sa.Column('false_negative_rate', sa.Float(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('threshold_source', sa.String(), nullable=True),
    sa.Column('confusion_matrix_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['training_runs.run_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_table('model_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('model_type', sa.String(), nullable=False),
    sa.Column('strategy', sa.String(), nullable=False),
    sa.Column('checkpoint_path', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('f1', sa.Float(), nullable=True),
    sa.Column('roc_auc', sa.Float(), nullable=True),
    sa.Column('pr_auc', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['training_runs.run_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_versions_model_version'), 'model_versions', ['model_version'], unique=True)
    op.create_table('privacy_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('dp_enabled', sa.Boolean(), nullable=True),
    sa.Column('secure_aggregation_enabled', sa.Boolean(), nullable=True),
    sa.Column('epsilon', sa.Float(), nullable=True),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('noise_multiplier', sa.Float(), nullable=True),
    sa.Column('clipping_norm', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['training_runs.run_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_table('round_clients',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('num_examples', sa.Integer(), nullable=True),
    sa.Column('train_loss', sa.Float(), nullable=True),
    sa.Column('val_loss', sa.Float(), nullable=True),
    sa.Column('training_time', sa.Float(), nullable=True),
    sa.Column('communication_time', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['training_runs.run_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('security_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['training_runs.run_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_events_event_id'), 'security_events', ['event_id'], unique=True)
    op.create_table('training_rounds',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('clients_selected', sa.Integer(), nullable=True),
    sa.Column('clients_completed', sa.Integer(), nullable=True),
    sa.Column('num_examples', sa.Integer(), nullable=True),
    sa.Column('train_loss', sa.Float(), nullable=True),
    sa.Column('val_loss', sa.Float(), nullable=True),
    sa.Column('global_accuracy', sa.Float(), nullable=True),
    sa.Column('global_precision', sa.Float(), nullable=True),
    sa.Column('global_recall', sa.Float(), nullable=True),
    sa.Column('global_f1', sa.Float(), nullable=True),
    sa.Column('global_roc_auc', sa.Float(), nullable=True),
    sa.Column('global_pr_auc', sa.Float(), nullable=True),
    sa.Column('round_duration', sa.Float(), nullable=True),
    sa.Column('aggregation_duration', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['training_runs.run_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_rounds')
    op.drop_index(op.f('ix_security_events_event_id'), table_name='security_events')
    op.drop_table('security_events')
    op.drop_table('round_clients')
    op.drop_table('privacy_configs')
    op.drop_index(op.f('ix_model_versions_model_version'), table_name='model_versions')
    op.drop_table('model_versions')
    op.drop_table('global_metrics')
    op.drop_index(op.f('ix_training_runs_run_id'), table_name='training_runs')
    op.drop_table('training_runs')
    op.drop_index(op.f('ix_experiments_experiment_id'), table_name='experiments')
    op.drop_table('experiments')
    op.drop_index(op.f('ix_clients_client_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
