"""Add PrivacyConfig table

Revision ID: a62668049dbe
Revises: a6e615fff870
Create Date: 2026-09-13 20:42:16.434510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a62668049dbe'
down_revision: Union[str, None] = 'a6e615fff870'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('privacy_configs', sa.Column('enabled', sa.Boolean(), nullable=False))
    op.add_column('privacy_configs', sa.Column('dp_mode', sa.String(), nullable=False))
    op.add_column('privacy_configs', sa.Column('target_epsilon', sa.Float(), nullable=True))
    op.add_column('privacy_configs', sa.Column('epsilon_spent', sa.Float(), nullable=True))
    op.add_column('privacy_configs', sa.Column('max_grad_norm', sa.Float(), nullable=True))
    op.add_column('privacy_configs', sa.Column('secure_rng', sa.Boolean(), nullable=False))
    op.drop_constraint(op.f('privacy_configs_run_id_key'), 'privacy_configs', type_='unique')
    op.create_index(op.f('ix_privacy_configs_run_id'), 'privacy_configs', ['run_id'], unique=True)
    op.drop_constraint(op.f('privacy_configs_run_id_fkey'), 'privacy_configs', type_='foreignkey')
    op.create_foreign_key(None, 'privacy_configs', 'training_runs', ['run_id'], ['run_id'], ondelete='CASCADE')
    op.drop_column('privacy_configs', 'dp_enabled')
    op.drop_column('privacy_configs', 'clipping_norm')
    op.drop_column('privacy_configs', 'secure_aggregation_enabled')
    op.drop_column('privacy_configs', 'epsilon')
    op.create_index(op.f('ix_training_rounds_run_id'), 'training_rounds', ['run_id'], unique=False)
    op.drop_constraint(op.f('training_rounds_run_id_fkey'), 'training_rounds', type_='foreignkey')
    op.create_foreign_key(None, 'training_rounds', 'training_runs', ['run_id'], ['run_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'training_rounds', type_='foreignkey')
    op.create_foreign_key('training_rounds_run_id_fkey', 'training_rounds', 'training_runs', ['run_id'], ['run_id'])
    op.drop_index(op.f('ix_training_rounds_run_id'), table_name='training_rounds')
    op.add_column('privacy_configs', sa.Column('epsilon', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('privacy_configs', sa.Column('secure_aggregation_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('privacy_configs', sa.Column('clipping_norm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('privacy_configs', sa.Column('dp_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'privacy_configs', type_='foreignkey')
    op.create_foreign_key(op.f('privacy_configs_run_id_fkey'), 'privacy_configs', 'training_runs', ['run_id'], ['run_id'])
    op.drop_index(op.f('ix_privacy_configs_run_id'), table_name='privacy_configs')
    op.create_unique_constraint(op.f('privacy_configs_run_id_key'), 'privacy_configs', ['run_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('privacy_configs', 'secure_rng')
    op.drop_column('privacy_configs', 'max_grad_norm')
    op.drop_column('privacy_configs', 'epsilon_spent')
    op.drop_column('privacy_configs', 'target_epsilon')
    op.drop_column('privacy_configs', 'dp_mode')
    op.drop_column('privacy_configs', 'enabled')
    # ### end Alembic commands ###
