"""add fault tolerance fields

Revision ID: a6e615fff870
Revises: b395ec09faed
Create Date: 2026-09-13 18:54:40.607322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6e615fff870'
down_revision: Union[str, None] = 'b395ec09faed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('round_clients', sa.Column('failure_reason', sa.String(), nullable=True))
    op.add_column('round_clients', sa.Column('retry_count', sa.Integer(), nullable=True))
    op.add_column('round_clients', sa.Column('is_straggler', sa.Boolean(), nullable=True))
    op.add_column('round_clients', sa.Column('update_valid', sa.Boolean(), nullable=True))
    op.add_column('round_clients', sa.Column('rejected_reason', sa.String(), nullable=True))
    op.add_column('round_clients', sa.Column('client_duration_seconds', sa.Float(), nullable=True))
    op.add_column('round_clients', sa.Column('communication_duration_seconds', sa.Float(), nullable=True))
    op.add_column('training_rounds', sa.Column('clients_failed', sa.Integer(), nullable=True))
    op.add_column('training_rounds', sa.Column('clients_rejected', sa.Integer(), nullable=True))
    op.add_column('training_rounds', sa.Column('clients_timed_out', sa.Integer(), nullable=True))
    op.add_column('training_rounds', sa.Column('straggler_count', sa.Integer(), nullable=True))
    op.add_column('training_rounds', sa.Column('dropout_rate', sa.Float(), nullable=True))
    op.add_column('training_rounds', sa.Column('completion_rate', sa.Float(), nullable=True))
    op.add_column('training_rounds', sa.Column('round_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_rounds', 'round_status')
    op.drop_column('training_rounds', 'completion_rate')
    op.drop_column('training_rounds', 'dropout_rate')
    op.drop_column('training_rounds', 'straggler_count')
    op.drop_column('training_rounds', 'clients_timed_out')
    op.drop_column('training_rounds', 'clients_rejected')
    op.drop_column('training_rounds', 'clients_failed')
    op.drop_column('round_clients', 'communication_duration_seconds')
    op.drop_column('round_clients', 'client_duration_seconds')
    op.drop_column('round_clients', 'rejected_reason')
    op.drop_column('round_clients', 'update_valid')
    op.drop_column('round_clients', 'is_straggler')
    op.drop_column('round_clients', 'retry_count')
    op.drop_column('round_clients', 'failure_reason')
    # ### end Alembic commands ###
