"""add mlflow columns

Revision ID: b395ec09faed
Revises: 0274cb5eb6c5
Create Date: 2026-09-13 18:40:03.470341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b395ec09faed'
down_revision: Union[str, None] = '0274cb5eb6c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_versions', sa.Column('mlflow_run_id', sa.String(), nullable=True))
    op.add_column('training_runs', sa.Column('mlflow_run_id', sa.String(), nullable=True))
    op.add_column('training_runs', sa.Column('mlflow_experiment_id', sa.String(), nullable=True))
    op.add_column('training_runs', sa.Column('mlflow_tracking_uri', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_runs', 'mlflow_tracking_uri')
    op.drop_column('training_runs', 'mlflow_experiment_id')
    op.drop_column('training_runs', 'mlflow_run_id')
    op.drop_column('model_versions', 'mlflow_run_id')
    # ### end Alembic commands ###
